PackageInstaller: Fix FC when tapping on a downloaded apk notification
java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/my_downloads/831 from pid=25212, uid=10019 requires android.permission.INTERNET, or grantUriPermission()

Change-Id: I61d60cff0ab1c9e7ac5ec293d35151c17bf57b83
Signed-off-by: Alex Naidis <alex.naidis@linux.com>